### ISSUE TITLE
Requires >= R 4.0, but not available for R version 4.0.0?

### ISSUE THREAD

**Issue by morganx** [waldronlab/lefser#13]
What am I missing?
Thanks.

> BiocManager::install("lefser")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.0 (2020-04-24)
Installing package(s) 'lefser'
Warning message:
package ‘lefser’ is not available (for R version 4.0.0) 
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_NZ.UTF-8/en_NZ.UTF-8/en_NZ.UTF-8/C/en_NZ.UTF-8/en_NZ.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phyloseq_1.32.0

**Comment by morganx** [comment]
Update:
This works.
install_github("waldronlab/lefser")

Installing from bioconductor still doesn't work because it thinks it's incompatible with my version of R.

**Comment by LiNk-NY** [comment]
I think this may have been due to a configuration issue. Or that `lefser` was not available for your version of Bioconductor at the time. If you still have issues, feel free to reopen. 
Best,
Marcel
