### ISSUE TITLE
Error in .local(.Object, ...) : ‘x’ and ‘y’ do not contain data

### ISSUE THREAD

**Issue by dannynielsen0** [waldronlab/lefser#19]
I have created the attached summarized experiment for analysis, but keep getting the following errors when I try to run lefser.

I have followed the tutorial for creating the summarized experiment and running the analysis, so I am hoping you can tell me if I have some bug in my code:

#create the SE - I transpose the counts data as it needs to match # rows with # cols
throat_exp <- SummarizedExperiment(assays=list(counts=t(counts)),
                                   colData=colData)

#should be simple to then run the lefser

throat_res <- lefser(expr=throat_exp, groupCol = "Staph.culture", blockCol = "Location")

#the above line generates the following error:
Error in .local(.Object, ...) : ‘x’ and ‘y’ do not contain data

[throat_exp.RDS.zip](https://github.com/waldronlab/lefser/files/9029527/throat_exp.RDS.zip)

**Comment by LiNk-NY** [comment]
Hi @dannynielsen0 
There are some empty groups in your `Location` variable. I have included a `droplevels` call in the PR linked above.
