### ISSUE TITLE
Conversion to relative abundance prior to lefser analysis

### ISSUE THREAD

**Issue by agatadziegiel** [waldronlab/lefser#21]
Hi,

I am relatively new to using the tool but the implementation of LEfSe in R is very helpful! 
I have done some reading on LEfSe and it seems that many users (and the LEfSe paper) indicate that counts should be converted to relative abundances before analysis. I was wondering whether this is done automatically with lefser or if the user needs to do this first? I have tried looking at the example dataset and it seems that raw counts are used but I am not sure. 

Thanks in advance!

**Comment by coralzhang** [comment]
I wonder if you have an answer to this yet? Should I normalize the data manually first?

**Comment by lwaldron** [comment]
Sincere apologies that we missed your question earlier... I'm working to identify a new maintainer for the package, and looking into the answer to this question.

**Comment by lwaldron** [comment]
To belatedly answer your question, yes, the data must be normalized manually first. Please accept our apologies for the delay and lack of documentation here.
