### ISSUE TITLE
Error in cols * 0.05 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by chuynh96** [waldronlab/lefser#24]
Hello,

I was able to convert my phyloseq object (output from the DADA2 pipeline) into a SummarizedExperiment object such that it mirrors the example SummarizedExperiment from the vignette (zeller14). However, using lefser(MySE, groupCol = "study_condition"), I keep getting this error: Error in cols * 0.05 : non-numeric argument to binary operator

I have no idea why I'm getting this error! I also attempted to use relative abundance rather than raw counts (although it appears the example zeller14 SummarizedExperiment just has raw counts) to see if it would prevent the error, to no avail.

Any advice anyone?

**Comment by asyakhl** [comment]
Hi @chuynh96,
cols is a numeric vector, which has your abundance values per feature. I would check that all of your abundance values are numeric. Or check that MySE is set up similarly to assay(zeller14). If that doesn't resolve this issue, could you point me to your dataset and conditions with which you run lefser.

**Comment by LiNk-NY** [comment]
@chuynh96 
Any updates on this?

**Comment by lwaldron** [comment]
Closing as error is not reproducible.
