### ISSUE TITLE
 Error in lda.default(x, grouping, ...)

### ISSUE THREAD

**Issue by J5886** [waldronlab/lefser#37]
Hello,

I'm using the lefser package with HUMAnN3 pathways output, 

I created a phyloseq object and then converted it to a tse object to run Lefser, 
but i got this erorr

`res <- lefser(tse_lefobj, groupCol = "Treatment")`

Error in lda.default(x, grouping, ...) : 
  variables   3  12  18  29  64  96 112 appear to be constant within groups

Could you please tell me, what should I do to fix it?

Thank you in advance

**Comment by LiNk-NY** [comment]
It sounds like you have the same values across groups in a grouping variable e.g., "Treatment". 
In order to better assist you, could you provide a minimally reproducible example?
https://stackoverflow.com/a/5963610/6558242
Thank you.

**Comment by J5886** [comment]
> @J5886 It sounds like you have the same values across groups in a grouping variable e.g., "Treatment". In order to better assist you, could you provide a minimally reproducible example? https://stackoverflow.com/a/5963610/6558242 Thank you.

Hi @LiNk-NY,
thanks for your rapid response and assistance,

**Comment by lwaldron** [comment]
@J5886 this issue should be resolved in recent versions of lefser - please try again and let us know if it persists.

**Comment by J5886** [comment]
> @J5886 this issue should be resolved in recent versions of lefser - please try again and let us know if it persists.

Hi @lwaldron thanks for letting me know.
Regards!
