### ISSUE TITLE
Error in svd(X, nu = 0L) : a dimension is zero

### ISSUE THREAD

**Issue by jdaledge** [waldronlab/lefser#47]
Hello :)

I'm having some issue with the lefser tool. I constructed a summarizedExperiment file for my data, with:

![image](https://github.com/waldronlab/lefser/assets/173885119/13385fac-04a4-4b69-afe0-fef74656b35c)

where **count_matrix** was my relative abundance counts with rownames= bacterial species and Colnames= sample ID

and **meta** was my metadata, with colnames= type of metadata and rownames= c(1:54)

the SE looks like this:

![image](https://github.com/waldronlab/lefser/assets/173885119/fa43a552-bc83-401e-b82d-d5801146b93b)

![image](https://github.com/waldronlab/lefser/assets/173885119/806380dc-6199-4e16-9ddf-aafd2ce53d5c)

I compared it to the Zeller14 SE to make sure it was structured the same, I had to additionally add the  em and em1

![image](https://github.com/waldronlab/lefser/assets/173885119/6fdf21ab-ce85-4a9d-8ca3-05fff8e2c5d1)

because i was getting the **Error in svd(X, nu = 0L) : a dimension is zero** Error, and when comparing to the zeller14 SE, I could see that they had these DFs in the elementMetadata, so I created them and added them to my se. now it looks identical to the Zeller14 setup in my opinion, but I am still getting the same error:

![image](https://github.com/waldronlab/lefser/assets/173885119/51b6f922-9d67-47f3-abe3-8fac83ce001e)

Can you help me find the error? or does anyone have any insight into how the zeller14 SE was constructed?

Thank you in advance!

J

**Comment by shbrief** [comment]
Hi @jdaledge, could you share your data so I can reproduce this error?

**Comment by jdaledge** [comment]
hi @shbrief , thanks for your reply,

Yes, I hope it it ok in this format, I have the original data file and then my rmarkdown as a word file so you can retrace my steps, let me know if you need anything else from me :)

cheers,
J

[lefse.xlsx](https://github.com/user-attachments/files/16025269/lefse.xlsx)
[lefse_attempt.docx](https://github.com/user-attachments/files/16025464/lefse_attempt.docx)

**Comment by jdaledge** [comment]
Ah, quick update, I just thought I solved it, because I saw that my count matrix had some rows which were all 0s, so I deleted them  from the excel file

[lefse.xlsx](https://github.com/user-attachments/files/16026198/lefse.xlsx)

and then ran everything again, but I still got the same error sadly..

**Comment by shbrief** [comment]
@jdaledge, I can't reproduce your code/error. This line `rowdata=rowdata %>% remove_rownames %>% column_to_rownames(var="Name")` doesn't work because the values under the `Name` column have duplicates and NA. Could you share the reproducible example? Also, share your code as a R file instead of docx file.

**Comment by jdaledge** [comment]
Hi,

Hopefully this works via email, as the R file is not supported on the Github forum.

Thanks again for your help,
J
________________________________

**Comment by lwaldron** [comment]
Hi @jdaledge , here is a simplified reproducible example I worked out below. Some observations:
1. the `blockCol` argument is intended for subclasses of the `groupCol`, which patient is not, so I omitted this argument since specimen type has no subclasses in your analysis.
2. However the presence of multiple measurements per patient likely inflates statistical significance, so you would want to either average these measurements by patient prior to analysis, or use a linear random-effects model to account for it, if you seek valid p-values. Not caring about the actual p-values, I changed the `lda.threshold` to 4 to get a more reasonable number of top hits to view. You have to set `kruskal.threshold` to something below 5e-11 to remove many hits, probably both for the reason I mentioned and because feces and buccal samples harbor very different bacteria. The reality is that all or nearly all of these taxa probably are truly differentially abundant between the two sites.
3. LDA can have undesirable behavior in the presence of synthetic clades (like "Bacteria" and other higher-level taxonomic ranks that are calculated rather than measured. This is likely the cause of the "variables are collinear" warning that appears in the fixed examples, because you have synthetic clades and measured variables that are identical or nearly identical.

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(lefser)
})

url <- "https://github.com/user-attachments/files/16025269/lefse.xlsx"
download.file(url, "lefse.xlsx")

bucfec <- read_excel("lefse.xlsx", sheet = "Buccal_fecal", skip = 2) |>
  as.data.frame()
#> New names:
#> • `HPNO1` -> `HPNO1...2`
#> • `HPNO1` -> `HPNO1...3`
#> • `HPNO2` -> `HPNO2...4`
#> • `HPNO2` -> `HPNO2...5`
#> • `HPNO3` -> `HPNO3...6`
#> • `HPNO3` -> `HPNO3...7`
#> • `HPNO4` -> `HPNO4...8`
#> • `HPNO5` -> `HPNO5...9`
#> • `HPNO5` -> `HPNO5...10`
#> • `HPNO6` -> `HPNO6...11`
#> • `HPNO6` -> `HPNO6...12`
#> • `HPNO7` -> `HPNO7...13`
#> • `HPNO7` -> `HPNO7...14`
#> • `HPNO9` -> `HPNO9...15`
#> • `HPNO10` -> `HPNO10...16`
#> • `HPNO12` -> `HPNO12...17`
#> • `HPNO12` -> `HPNO12...18`
#> • `HPNO13` -> `HPNO13...19`
#> • `HPNO13` -> `HPNO13...20`
#> • `HPNO14` -> `HPNO14...21`
#> • `HPNO14` -> `HPNO14...22`
#> • `HPNO15` -> `HPNO15...23`
#> • `HPNO15` -> `HPNO15...24`
#> • `HPNO16` -> `HPNO16...25`
#> • `HPNO16` -> `HPNO16...26`
#> • `HPNO1` -> `HPNO1...27`
#> • `HPNO1` -> `HPNO1...28`
#> • `HPNO2` -> `HPNO2...29`
#> • `HPNO2` -> `HPNO2...30`
#> • `HPNO3` -> `HPNO3...31`
#> • `HPNO3` -> `HPNO3...32`
#> • `HPNO4` -> `HPNO4...33`
#> • `HPNO4` -> `HPNO4...34`
#> • `HPNO5` -> `HPNO5...35`
#> • `HPNO5` -> `HPNO5...36`
#> • `HPNO6` -> `HPNO6...37`
#> • `HPNO6` -> `HPNO6...38`
#> • `HPNO7` -> `HPNO7...39`
#> • `HPNO7` -> `HPNO7...40`
#> • `HPNO9` -> `HPNO9...41`
#> • `HPNO9` -> `HPNO9...42`
#> • `HPNO10` -> `HPNO10...43`
#> • `HPNO10` -> `HPNO10...44`
#> • `HPNO12` -> `HPNO12...45`
#> • `HPNO12` -> `HPNO12...46`
#> • `HPNO13` -> `HPNO13...47`
#> • `HPNO13` -> `HPNO13...48`
#> • `HPNO14` -> `HPNO14...49`
#> • `HPNO14` -> `HPNO14...50`
#> • `HPNO15` -> `HPNO15...51`
#> • `HPNO15` -> `HPNO15...52`
#> • `HPNO16` -> `HPNO16...53`
#> • `HPNO16` -> `HPNO16...54`
```

``` r
rownames(bucfec) <- bucfec[, 1]
bucfec <- bucfec[, -1] |> 
  as.matrix()

md <- read_excel("lefse.xlsx", n_max = 2) |> t()
colnames(md) <- md[1, ]
md <- md[-1, ] |> as.data.frame()
rownames(md) <- colnames(bucfec)

se <- SummarizedExperiment(assays = list(counts = bucfec), colData = md)
se <- se[rowSums(assay(se)) > 0.001, ]

# looks like it was normalized to relative abundance with sum 1
colSums(assay(se)) |> summary()
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  0.9613  0.9850  0.9941  0.9918  1.0013  1.0101
```

``` r

# Use relativeAb to scale to sum 1e6
se <- relativeAb(se)

# collinearity caused by synthetic clades (like "Bacteria (Unknown)")
res <- lefser(se, groupCol = "Type", lda.threshold = 4)
#> The outcome variable is specified as 'Type' and the reference category is 'Buccal'.
#>  See `?factor` or `?relevel` to change the reference category.
#> Warning in lda.default(x, grouping, ...): variables are collinear
```

``` r
lefserPlot(res)
```

![](https://i.imgur.com/IabVYAH.png)

``` r

sessionInfo()
#> R version 4.4.0 (2024-04-24)
#> Platform: aarch64-apple-darwin20
#> Running under: macOS Sonoma 14.4.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> time zone: Europe/Rome
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats4    stats     graphics  grDevices utils     datasets  methods  
#> [8] base     
#> 
#> other attached packages:
#>  [1] lefser_1.15.1               SummarizedExperiment_1.34.0
#>  [3] Biobase_2.64.0              GenomicRanges_1.56.0       
#>  [5] GenomeInfoDb_1.40.0         IRanges_2.38.0             
#>  [7] S4Vectors_0.42.0            BiocGenerics_0.50.0        
#>  [9] MatrixGenerics_1.16.0       matrixStats_1.3.0          
#> [11] readxl_1.4.3                lubridate_1.9.3            
#> [13] forcats_1.0.0               stringr_1.5.1              
#> [15] dplyr_1.1.4                 purrr_1.0.2                
#> [17] readr_2.1.5                 tidyr_1.3.1                
#> [19] tibble_3.2.1                ggplot2_3.5.1              
#> [21] tidyverse_2.0.0            
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.2.1        farver_2.1.2            libcoin_1.0-10         
#>  [4] R.utils_2.12.3          fastmap_1.2.0           TH.data_1.1-2          
#>  [7] reprex_2.1.0            digest_0.6.35           timechange_0.3.0       
#> [10] lifecycle_1.0.4         survival_3.7-0          magrittr_2.0.3         
#> [13] compiler_4.4.0          rlang_1.1.4             tools_4.4.0            
#> [16] utf8_1.2.4              yaml_2.3.8              knitr_1.47             
#> [19] labeling_0.4.3          S4Arrays_1.4.1          DelayedArray_0.30.1    
#> [22] abind_1.4-5             multcomp_1.4-25         R.cache_0.16.0         
#> [25] withr_3.0.0             R.oo_1.26.0             grid_4.4.0             
#> [28] fansi_1.0.6             colorspace_2.1-0        scales_1.3.0           
#> [31] MASS_7.3-60.2           cli_3.6.2               mvtnorm_1.2-5          
#> [34] rmarkdown_2.27          crayon_1.5.2            generics_0.1.3         
#> [37] rstudioapi_0.16.0       httr_1.4.7              tzdb_0.4.0             
#> [40] zlibbioc_1.50.0         modeltools_0.2-23       splines_4.4.0          
#> [43] parallel_4.4.0          cellranger_1.1.0        XVector_0.44.0         
#> [46] vctrs_0.6.5             Matrix_1.7-0            sandwich_3.1-0         
#> [49] jsonlite_1.8.8          hms_1.1.3               glue_1.7.0             
#> [52] codetools_0.2-20        stringi_1.8.4           gtable_0.3.5           
#> [55] UCSC.utils_1.0.0        munsell_0.5.1           styler_1.10.3          
#> [58] pillar_1.9.0            htmltools_0.5.8.1       GenomeInfoDbData_1.2.12
#> [61] R6_2.5.1                evaluate_0.23           lattice_0.22-6         
#> [64] R.methodsS3_1.8.2       SparseArray_1.4.8       xfun_0.44              
#> [67] coin_1.4-3              fs_1.6.4                zoo_1.8-12             
#> [70] pkgconfig_2.0.3
```

<sup>Created on 2024-07-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jdaledge** [comment]
amazing, thank you so much!

**Comment by lwaldron** [comment]
You're welcome!
