### ISSUE TITLE
cannot find get_terminal_nodes function

### ISSUE THREAD

**Issue by yasir-binfo** [waldronlab/lefser#57]

**Comment by shbrief** [comment]
Hi @yasir-binfo 
`get_terminal_nodes` function is currently available only in the Bioconductor devel branch (above v.1.15.3). Can you double-check the version of the installed package? Thanks.

**Comment by yasir-binfo** [comment]
Yes it works thank you

**Comment by yasir-binfo** [comment]
Hi Sehyun

My next question is can we do multiple group analysis as I have 6 groups
and lefser gives  pairwise comparison is there any possibility or I have to
aggregate the pairwise results manually?

Thanks for your support

**Comment by shbrief** [comment]
Hi @yasir-binfo 
Unfortunately, _lefser_ doesn't support multiple groups, but it is the new feature we're working on now. Thanks!

**Comment by yasir-binfo** [comment]
Many thanks for response
