### ISSUE TITLE
`lefserClades` shouldn't restrict to species

### ISSUE THREAD

**Issue by shbrief** [waldronlab/lefser#71]
https://github.com/waldronlab/lefser/blob/bcc921da1b0fd2a33f43a33b11e3521cf7357a9a/R/lefserPlotClad.R#L182

Hard-coding the tip to species will mostly work for WMS but breaks for 16S data, which has a lower resolution. Instead, 'restriction' should be applied to the lowest taxonomic level where non-NA value is available.

**Comment by sdgamboa** [comment]
I can fix it. I think the lowest resolution for 16S data is genus, though (OTUs?).

**Comment by shbrief** [comment]
The genus is considered a reliable level for 16S. But I think it's better to use the lowest level that starts to capture information to cover different cases. Also, with a bit more information in a message like, "Dropped ## features without $$-level information."

**Comment by shbrief** [comment]
19c80f58505617c0f1469e8f1da96d9481a18cf2
