### ISSUE TITLE
How to set LDA score cutoff and Kruskal-Wallis p-value cutoff?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/lefser#8]
Analyses using LEfSE usually state an LDA score cutoff and a Kruskal-Wallis p-value cutoff. I can see how the LDA score cutoff is possible through manual filtering of the lefserAnalysis output, but can't see how to do it for p-value. 

Document how to adjust these thresholds in the vignette.

**Comment by lwaldron** [comment]
Document:
```
#' @param kw.threshold
#' @param wilcoxon.threshold
```

**Comment by lwaldron** [comment]
Document how to set a LDA effect size threshold?

**Comment by asyakhl** [comment]
I had added the LDA cutoff, I created a branch for that.
